/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { TodoList as TodoTask } from './components/task/task';

interface HTMLTodoTaskElement extends TodoTask, HTMLElement {
}
declare var HTMLTodoTaskElement: {
  prototype: HTMLTodoTaskElement;
  new (): HTMLTodoTaskElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "todo-task": HTMLTodoTaskElement;
  }
  interface ElementTagNameMap {
      "todo-task": HTMLTodoTaskElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "todo-task": JSXElements.TodoTaskAttributes;
      }
  }
  namespace JSXElements {
      export interface TodoTaskAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          title?: string,
          completed?: boolean
      }
  }
}

import { TodoList as TodoList } from './components/todo-list/todo-list';

interface HTMLTodoListElement extends TodoList, HTMLElement {
}
declare var HTMLTodoListElement: {
  prototype: HTMLTodoListElement;
  new (): HTMLTodoListElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "todo-list": HTMLTodoListElement;
  }
  interface ElementTagNameMap {
      "todo-list": HTMLTodoListElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "todo-list": JSXElements.TodoListAttributes;
      }
  }
  namespace JSXElements {
      export interface TodoListAttributes extends HTMLAttributes {
          mode?: string,
          color?: string,
        
          title?: string
      }
  }
}

